name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.10  # This sets up a conda environment with Python 3.10

    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name myenv
        # Activate the environment so that subsequent commands use it
        source $(conda info --base)/etc/profile.d/conda.sh
        conda activate myenv

    - name: Lint with flake8
      run: |
        conda install -n myenv flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        conda install -n myenv pytest
        pytest
